### ISSUE TITLE
Preparing Gajraj One for release on Google Fonts

### ISSUE THREAD

**Issue by yanone** [xconsau/GajrajOne#1]
Hello,

I'm commissioned to prepare Gajraj One for release on Google Fonts.

The fonts are in near-perfect technical condition. I would like to ask you for the following:

* Set `OS/2.usWinDescent` to `515`
* Add a description file to the repository akin to https://github.com/google/fonts/blob/main/ofl/benne/DESCRIPTION.en_us.html (2000 character maximum incl. whitespace and HTML
* Add latest font files to the repository. The build artifacts of the Actions are expired, so I couldn't download them. I checked the file in `font/Regular/GajrajOne-Regular.ttf` which only showed the above-mentioned `winDescent` value as being problematic. Alternatively, please make a so-called release as part of the Actions build. The template should contain instructions on how to do that.
* If you haven't already, please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSeMwHN8J213ZaxHrr5lHCrX56HY_NjGrWB8o604g98YxuMrdA/viewform) for your designer profile information.

Thank you for your cooperation. Please let me know here when to check the files again.

**Comment by xconsau** [comment]
Hello Yanone,

Glad to have you onboard.

- The `OS/2.usWinDescent` has been set to `515` now. However,  the absolute sum of the hhea metrics is coming around 1.69x of the font's UPM.
- Description file `DESCRIPTION.en_us.html` has been added now.
- Latest source files have been updated. The compiled binaries are inside the release zip folder.
- Designer profile information form has been filled and submitted.

I would also like to add that there is some work needed in fixing curve quality. There are some jaggy segments and multiple nodes which I need to cleanup in the glif files. I will update you once I complete this. Please let me know if there are any technical or design issues in the meanwhile.

Thanks and kind regards

**Comment by yanone** [comment]
> * The `OS/2.usWinDescent` has been set to `515` now. However,  the absolute sum of the hhea metrics is coming around 1.69x of the font's UPM.

The other metrics didn't need changing. I asked specifically to only alter `winDescent`. Please revert all other metrics changes that you made except this one.

The `hhea` & `typo` metrics are used to adjust the line height (when "Use Typo Metrics" is set, which it is) , while `win` metrics affect the clipping of glyphs top and bottom dominantly in Microsoft apps. These need to be set independently to match the highest and lowest points of glyphs and components, while the other metrics are used to determine the line height.

Please let me know once you're done with any changes on your side.
There are no more technical issues to my knowledge.

Thank you.

**Comment by xconsau** [comment]
Changes made as required. Other values reverted back to the previous ones, and only the `OS/2.usWinDescent` modified. The release zip has been updated as well.

**Comment by yanone** [comment]
Thank you. There are no more technical issue left. Please let me know when you're done with the outline quality adjustments.

**Comment by xconsau** [comment]
That's great. I will update you soon.

**Comment by xconsau** [comment]
Hello @yanone. Outlines and curves have been improved now. The release binaries have been updated as well.

**Comment by xconsau** [comment]
Hello @yanone, can you acknowledge if you have notified with my previous message. (Sorry for the ping). :)

**Comment by yanone** [comment]
I acknowledge your previous message.
My apologies. I've just returned from holidays, during which I actually don't look at or reply to anything. I will look at the fonts soon. There's a lot on my plate right now.

**Comment by xconsau** [comment]
No problem, Yanone. Appreciate your response. :)

**Comment by yanone** [comment]
So I was about to check your latest font today but couldn't find any. The [release](https://github.com/xconsau/GajrajOne/releases/tag/v1.000) is not updated and I can't find binaries in the repo either. Please note that they're not getting included because the `fonts` folder is excluded from updating through the `.gitignore` file, which is a default setting from the `googlefonts-project-template`. 

Please make another release for the binaries at least. Thank you.

**Comment by xconsau** [comment]
Hello @yanone,

I am not sure what you mean by "release is not updated", as it is updated on Dec 14 after the curve correction. I am able to download the release assets successfully and the fonts are present in it inside the `/fonts/ttf/` folder. Please see the attached screenshot:

![screenshot-github com-2023 01 19-21_05_10](https://user-images.githubusercontent.com/11784237/213485506-c047b07c-97de-4c1c-a1d6-ea400f78cad0.png)

Maybe because I have modified the same release 1.0.0 by deleting and reuploading the changed assets. I have also added the [font ttf](https://github.com/xconsau/GajrajOne/tree/main/fonts/ttf)  inside the source code, just in case you are not able to download the zip file from assets.

**Comment by yanone** [comment]
Ah yes, that's it. I only paid attention to the release date, Dec 6, and didn't notice the updated zip file. Will inspect it tomorrow. Thank you.

**Comment by xconsau** [comment]
No problem, Yanone. Thank you for your time.

**Comment by yanone** [comment]
Your font is in perfect condition. Thank you.
Please fill this form for your designer bio: https://docs.google.com/forms/d/e/1FAIpQLSeMwHN8J213ZaxHrr5lHCrX56HY_NjGrWB8o604g98YxuMrdA/viewform
Once done, I will send the font off to Google Fonts.

**Comment by xconsau** [comment]
Thanks very much. I have filled and submitted the Designer profile form.
